#FROM node:lts-alpine as build-stage
#WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN chmod -R 777 node_modules/.bin
#RUN npm run build

FROM oven/bun:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN bun install
COPY . .
RUN chmod -R 777 node_modules/.bin
RUN bun run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]